version: "2"

volumes:
  gems:
    driver: local
  postgres-data:
    driver: local

services:
  db:
    image: postgres:9.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "H4cH3R5ch00L!"
  web:
    image: ruby:2.3
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
    stdin_open: true
    tty: true
    depends_on:
      - db
    command: rails server -b 0.0.0.0 -p 3000 -P /tmp/rails.pid
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgres://postgres:H4cH3R5ch00L!@db:5432/hackerschool_dev?pool=25&encoding=unicode&schema_search_path=public,partitioning"
