# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 084ff246fcb9357c2e8469996e707db76a0e5f92e46d0d7d1b58556ea47d98a1303fbbb7fad9f74902f493afd031fff1c63a886bf3b10a6c87387781b81334a8

test:
  secret_key_base: c70c2d74bed6d7d510f2fb7ce7323887c3ebfd1409651b558285fd80ec16c6fe6d064798a58d2947b4a5d088c756f6dc0d8ea84b03c6bd4298521cdd782f4484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
